import React from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { TribalIcon, WarliStrip } from "@/components/TribalIcons";
import { KEYBOARD_SHORTCUTS, TRACKS } from "@/lib/constants";
import { Copyright } from "lucide-react";

function Section({ title, children }) {
  return (
    <div className="mb-5">
      <h3 className="text-[18px] font-bold text-[#e8dcc5] mb-2" style={{ fontFamily: "var(--font-display)" }}>{title}</h3>
      <div className="text-[17px] leading-relaxed text-[#cfc4ae] space-y-2">{children}</div>
    </div>
  );
}

export default function AboutDialog({ open, onOpenChange }) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="mmm-panel border-[hsl(26_14%_22%)] max-w-3xl max-h-[90vh] flex flex-col" data-testid="about-dialog">
        <DialogHeader>
          <DialogTitle className="text-[#f2ece1] text-2xl font-bold flex items-center gap-3" style={{ fontFamily: "var(--font-display)" }}>
            <span className="w-11 h-11 rounded-xl bg-[#2f6b4f] flex items-center justify-center">
              <TribalIcon name="spiral" size={22} color="#f2ece1" />
            </span>
            About · Mapping Memory, Mapping Meals
          </DialogTitle>
        </DialogHeader>

        <Tabs defaultValue="about" className="flex-1 flex flex-col min-h-0">
          <TabsList className="bg-[hsl(26_16%_14%)] rounded-xl w-full justify-start gap-1 h-11">
            <TabsTrigger value="about" data-testid="about-tab-about" className="rounded-lg text-[17px] data-[state=active]:bg-[#d07a3a] data-[state=active]:text-[#14100b]">The Experience</TabsTrigger>
            <TabsTrigger value="how" data-testid="about-tab-how" className="rounded-lg text-[17px] data-[state=active]:bg-[#d07a3a] data-[state=active]:text-[#14100b]">How it Works</TabsTrigger>
            <TabsTrigger value="shortcuts" data-testid="about-tab-shortcuts" className="rounded-lg text-[17px] data-[state=active]:bg-[#d07a3a] data-[state=active]:text-[#14100b]">Keyboard</TabsTrigger>
            <TabsTrigger value="credits" data-testid="about-tab-credits" className="rounded-lg text-[17px] data-[state=active]:bg-[#d07a3a] data-[state=active]:text-[#14100b]">Credits & Licensing</TabsTrigger>
          </TabsList>

          <TabsContent value="about" className="flex-1 min-h-0 mt-4">
            <div className="pr-4 overflow-y-auto" style={{ maxHeight: "54vh" }}>
              <Section title="Explore West Bengal's Indigenous Food Heritage">
                <p>
                  Explore a selection of West Bengal's cultural landmarks and food heritage through immersive,
                  audio-guided tours generated with the help of AI. This deep map documents <b>100 living food
                  traditions</b> of <b>16 indigenous tribal communities</b> — Toto, Santal, Oraon, Rajbanshi, Lodha,
                  Kheria Sabar, Lepcha, Bhutia, Sherpa, Mech, Rabha, Garo, Munda, Bhumij, Birhor, Limbu and more —
                  across <b>14 layers of knowledge</b>: ecology, community, ethnobotany, culinary technology,
                  seasonality, folklore, lost traditions, sacred foods, medicine, cultural significance and deep
                  historical origins.
                </p>
                <p>
                  Select a location on the map or from a place card, explore the immersive 3D terrain view, press the
                  <b> Snapshot</b> button and enjoy audio commentary generated by AI. At any time you can press the
                  <b> “Reveal 5 Questions & Answers”</b> button, which generates five pedagogical questions — with
                  answers grounded in the archive — based on what you are viewing.
                </p>
                <p>
                  Audio narration is available in <b>English, বাংলা (Bengali) and हिन्दी (Hindi)</b>, spoken by your
                  browser's speech engine with a voice of your choosing. Authentic field-recorded tribal music plays
                  as you explore, changing with the community whose foods you are visiting.
                </p>
                <p>
                  This experience supports the <b>Indian Indigenous Knowledge System (IKS)</b> — built as a
                  pedagogical and preservation tool for researchers, students and communities. This first
                  experimentation works with a curated research database, with more communities and sites to be added
                  in the future.
                </p>
              </Section>
            </div>
          </TabsContent>

          <TabsContent value="how" className="flex-1 min-h-0 mt-4">
            <div className="pr-4 overflow-y-auto" style={{ maxHeight: "54vh" }}>
              <Section title="Understanding what you see">
                <p>
                  To understand the context of your current view, we use <b>Gemini — Google's multimodal model</b> —
                  which accepts multiple input modalities. The map view (its centre coordinates, zoom, visible
                  communities and food landmarks) is analysed and a rich description of the scene is created.
                </p>
              </Section>
              <Section title="Additional information">
                <p>
                  To gather more information, we use the <b>GPS coordinates</b> of each heritage site together with
                  the name of the location, community, ecology and the 14-layer research archive to feed into Gemini.
                  This provides deep cultural context for every narration.
                </p>
              </Section>
              <Section title="Generating a script">
                <p>
                  Once all the information is collected, Gemini writes an immersive tour script grounded strictly in
                  the research database. The script is then spoken in real time by your browser's speech synthesis
                  engine with emotional voice modulation (sentence-level pitch and pace shaping) in English, Bengali
                  or Hindi.
                </p>
              </Section>
              <Section title="AI content disclaimer">
                <p className="text-[#e3b448]">
                  ⚠ Audio comments and answers are generated by AI and may contain inaccurate content. Narrations are
                  grounded in the research archive but should not replace primary ethnographic sources.
                </p>
              </Section>
            </div>
          </TabsContent>

          <TabsContent value="shortcuts" className="flex-1 min-h-0 mt-4">
            <div className="pr-4 overflow-y-auto" style={{ maxHeight: "54vh" }}>
              <Section title="Keyboard shortcuts">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2" data-testid="keyboard-shortcuts-list">
                  {KEYBOARD_SHORTCUTS.map((s, i) => (
                    <div key={i} className="flex items-center gap-3 rounded-xl border border-[hsl(26_14%_20%)] bg-[hsl(26_18%_11%)] px-4 py-2.5">
                      <kbd className="font-mono text-[16px] font-bold text-[#e3b448] bg-[hsl(26_20%_16%)] border border-[hsl(26_14%_26%)] rounded-lg px-3 py-1 min-w-[64px] text-center">
                        {s.key}
                      </kbd>
                      <span className="text-[17px]">{s.action}</span>
                    </div>
                  ))}
                </div>
                <p className="mt-3 text-[16px] text-[#a08a68]">
                  Mouse / touch: drag to pan · scroll or pinch to zoom · right-click-drag (two-finger drag) to rotate
                  and tilt the 3D terrain.
                </p>
              </Section>
            </div>
          </TabsContent>

          <TabsContent value="credits" className="flex-1 min-h-0 mt-4">
            <div className="pr-4 overflow-y-auto" style={{ maxHeight: "54vh" }}>
              <Section title="Map data, terms & licensing">
                <p>
                  Interactive map rendered with <b>MapLibre GL JS</b> (open source, BSD licence) · Map experience
                  version 2.0 · Open access for research and education.
                </p>
                <ul className="list-disc list-inside space-y-1">
                  <li>Basemap © <b>CARTO</b> · Data © <b>OpenStreetMap contributors</b> (ODbL licence)</li>
                  <li>3D terrain elevation — <b>Mapzen / AWS Open Data Terrain Tiles</b> (open access)</li>
                  <li>State & district boundaries — open community GeoJSON (datameet / udit-001, open access)</li>
                  <li>Research data — “Mapping Memory, Mapping Meals” 14-layer deep-mapping database, compiled from 27 academic papers and field documentation</li>
                </ul>
              </Section>
              <Section title="Music credits — copyright-free / open access">
                <ul className="list-disc list-inside space-y-1">
                  {TRACKS.map((t) => (
                    <li key={t.id}>
                      <b>{t.name}</b> — {t.credit}
                    </li>
                  ))}
                </ul>
                <p className="text-[15.5px] text-[#a08a68]">
                  Field recordings courtesy Indira Gandhi Rashtriya Manav Sangrahalaya (IGRMS), National Museum of
                  Mankind, via archive.org · CC BY-NC 4.0. CC0 tracks via archive.org public domain collections.
                </p>
              </Section>
              <Section title="Background image sources">
                <p>
                  Immersive tour backgrounds are sourced from <b>Unsplash</b> (free-to-use licence) — forest, tea
                  garden, river, village, terracotta and paddy-field photography of Bengal and eastern India.
                </p>
              </Section>
              <Section title="Copyright">
                <div className="rounded-2xl border border-[#e3b44844] bg-[#2a2010] p-4 flex items-start gap-3" data-testid="copyright-note">
                  <Copyright size={22} className="text-[#e3b448] shrink-0 mt-0.5" />
                  <div>
                    <p className="font-bold text-[#f2ece1] text-[18px]">
                      © Simanta Nandi · Dr. Gigy J Alex
                    </p>
                    <p className="text-[17px]">
                      Indian Institute of Space Science and Technology, Thiruvananthapuram · 2026
                    </p>
                    <p className="text-[15.5px] text-[#a08a68] mt-1">
                      Research database, deep-mapping design and curation. All rights reserved over the research
                      compilation; map and media components remain under their respective open licences.
                    </p>
                  </div>
                </div>
              </Section>
              <div className="flex justify-center py-2">
                <WarliStrip count={7} size={18} />
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
